version: "3.9"
services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432"
    networks:
      - app_net
    environment:
      - POSTGRES_PASSWORD=postgres

  redis-server:
    image: redis:latest
    command: redis-server --requirepass 'redis'
    ports:
      - "6379"
    networks:
      - app_net

  web-service:
    image: ghcr.io/xii1/ea-project:$WEB_SERVICE_TAG
    ports:
      - "8080"
    restart: always
    networks:
      - app_net
    depends_on:
      - postgres-db
      - redis

  load-balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app_net
    depends_on:
      - web-service

networks:
  app_net:
