version: "3.9"
services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432"
    networks:
      - app_net
    environment:
      - POSTGRES_PASSWORD=postgres

  redis-server:
    image: redis:latest
    command: redis-server --requirepass 'redis'
    ports:
      - "6379"
    networks:
      - app_net

  web-service:
    image: web-service:1.0.0
    ports:
      - "8080"
    restart: always
    networks:
      - app_net
    depends_on:
      - postgres-db
      - redis-server

  load-balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/certs:/etc/nginx/certs
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - app_net
    depends_on:
      - web-service

networks:
  app_net:
