server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-base64: and0c2VjcmV0
  issuer: localhost
  expiration-in-hours: 1

redis:
  host: localhost
  port: 6379
  password: redis
  cache-expiration-in-hours: 1

logging:
  file:
    name: ./logs/application.log
